version: "1"
services:
  postgresdb:
    image: "timescale/timescaledb-ha:pg14.5-ts2.8.1-p1"
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_PASSWORD: "Pass1234!"
    networks:
      - backend
networks:
  backend: